version: '2'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
    - "5672:5672"
    - "15672:15672"
  notification-service:
    build: microservice-ecms-notification
    ports:
    - "8094:8094"
    expose:
    - "8094"
    links: 
    - rabbitmq
  rabbitmq-service:
    build: microservice-ecms-rabbitMQ
    ports:
    - "8092:8092"
    expose:
    - "8092"
    links: 
    - rabbitmq