info:
  component: Edge Server
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
zuul:
  prefix: /ecms/api
  routes:
    transcoding:
      path: /transcoding/**
      serviceId: transcoding-service
ribbon:
  eureka:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
    registerWithEureka: true
server:
  port: 8765
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG